services:
  tagger:
    container_name: tagger
    build: .
    ports:
      - "5013:5013"
    volumes:
      - /home/gaulerie/Desktop/NewFolder:/app/musics
      - ./covers:/app/covers
      - ./data:/app/data
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=changeme
      - SECRET_KEY=aReallySecretKey