ALLOWED_EXTENSIONS = ('.mp3', '.flac', '.m4a', '.mp4', '.ogg', '.wav')
MUSIC_FOLDER = '/app/musics'
PAGE_SIZE = 25
METADATA_KEYS = {
  "filename": ["filename"],
  "title": ["title","TIT2","©nam","TXXX:title","TXXX:©nam"],
  "artist": ["artist","TPE1","TPE2","TXXX:©ART","TXXX:artist","TXXX:ARTISTS","TSO2","TSOP"],
  "tsrc": ["TSRC","TXXX:tsrc"],
  "publisher": ["TMED","TXXX:publisher"],
  "producers": ["TEXT","TXXX:producers"],
  "album": ["album","TALB","©alb","TXXX:album","TXXX:©alb"],
  "year": ["year","TDRC","TDOR","©day","TXXX:originalyear","TXXX:©day","TXXX:year"],
  "genre": ["genre","TCON","©gen","TXXX:©gen","TXXX:genre"],
  "track": ["tracknumber","TRCK","TPOS","TXXX:track"],
  "bpm": ["TBPM","TXXX:bpm"],
  "key": ["TKEY","TXXX:key"],
  "length": ["TLEN","TXXX:length"],
  "label": ["TPUB","TCOP","TXXX:label"],
  "musicbrainz_artist_id": ["TXXX:MusicBrainz Artist Id","TXXX:musicbrainz_artist_id"],
  "musicbrainz_album_id": ["TXXX:MusicBrainz Album Id","TXXX:musicbrainz_album_id"],
  "spotify_url": ["WOAS","TXXX:spotify_url"],
  "barcode": ["TXXX:BARCODE","TXXX:barcode"],
  "catalog_number": ["TXXX:CATALOGNUMBER","TXXX:catalog_number"],
  "asin": ["TXXX:ASIN","TXXX:asin"],
  "media_type": ["TMED"],
  "musicbrainz_album_release_country": ["TXXX:MusicBrainz Album Release Country","TXXX:musicbrainz_album_release_country"],
  "musicbrainz_album_status": ["TXXX:MusicBrainz Album Status","TXXX:musicbrainz_album_status"],
  "musicbrainz_album_type": ["TXXX:MusicBrainz Album Type","TXXX:musicbrainz_album_type"],
  "musicbrainz_album_artist_id": ["TXXX:MusicBrainz Album Artist Id","TXXX:musicbrainz_album_artist_id"],
  "musicbrainz_release_group_id": ["TXXX:MusicBrainz Release Group Id","TXXX:musicbrainz_release_group_id"],
  "musicbrainz_release_track_id": ["TXXX:MusicBrainz Release Track Id","TXXX:musicbrainz_release_track_id"],
  "script": ["TXXX:SCRIPT","TXXX:script"],
  "ufid": ["UFID:http://musicbrainz.org","TXXX:ufid"],
  "comment": ["COMM:ID3v1 Comment","COMM","TXXX:comment"],
  "description": ["TXXX:description","COMM:desc"],
  "likes": ["TXXX:likes"],
  "dislikes": ["TXXX:dislikes"],
  "software": ["TSSE"],
  "views": ["TXXX:views"],
  "rating": ["TXXX:rating"],
  "download_date": ["TXXX:download_date"],
  "uploader": ["TXXX:uploader"],
  "purl": ["TXXX:purl","TXXX:comment"],
  "synopsis": ["TXXX:synopsis"],
  "acoustid_id": ["TXXX:Acoustid Id"],
  "copyright": ["TCOP"],
  "involved_people": ["TIPL"],
  "lyrics": ["LYRICS"],
  "cover_raw": ["APIC:Cover", "cover"],
  "cover_base_64": ["cover_base_64"],
}